// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("UIButton");

var defaultStyle = {
  backgroundColor: "white",
  border: "1px solid black",
  color: "black"
};

var primaryStyle = {
  backgroundColor: "blue",
  border: "1px solid blue",
  color: "white"
};

function makeStyle(use) {
  if (use) {
    switch (use[0]) {
      case "default" : 
          return defaultStyle;
      case "primary" : 
          return primaryStyle;
      default:
        return defaultStyle;
    }
  } else {
    return defaultStyle;
  }
}

function make(_, text, onClick, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("button", {
                  className: "bw0 br2 pa3 white fw1 tc tracked",
                  style: {
                    backgroundColor: "#4DB6AC",
                    cursor: "pointer",
                    outline: "none"
                  },
                  onClick: onClick
                }, text);
    });
  return newrecord;
}

exports.component    = component;
exports.defaultStyle = defaultStyle;
exports.primaryStyle = primaryStyle;
exports.makeStyle    = makeStyle;
exports.make         = make;
/* component Not a pure module */
